name: Deploy_Frontend_Config_Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'client/config/**'

defaults:
  run:
    working-directory: client/config

jobs:
  dev_config_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy config to development S3 bucket
      run: |
        aws s3 cp config.development.js s3://${{ secrets.S3_BUCKET_DEV }} --follow-symlinks
    - name: Invalidate cached config
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID_DEV }} --paths "config.development.js"
